wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: deeponet
dataset:
  desc: null
  value: L-shpae,8, subsquares
epochs:
  desc: null
  value: 6000
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718007923
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.17.1
      8:
      - 4
      - 5
      13: darwin-arm64
